name: mini

on: push

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_IP }}
          username: ${{ secrets.REMOTE_SSH_ID }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          script: |
            cd miniproject
            ^C
          # cd /home/ubuntu/Node.js_specialty
          # git pull origin master
          # npm install
          # pm2 restart app.js
