name: mini

on: push

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_IP }}
          username: ${{ secrets.REMOTE_SSH_ID }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          timeout: 40s # 30초 기본
          script: |
          cd /home/ubuntu/Node.js_specialty
          sudo git pull
          sudo npm install
          sudo pm2 restart app.js
